"use client";
import { useState } from "react";
import { BriefcaseBusiness, Building2, Check, Download, EllipsisVertical, ExternalLink, FileSearch, Folder, Globe, Home, LayoutGrid, Mail, Plus, RotateCcw, Settings, ShieldCheck, Users } from "lucide-react";
import * as UI from "../../../packages/ui/src";

export const exampleNavigation:UI.NavigationItem[]=[{id:"home",label:"Home",icon:<Home size={17}/>,href:"#home"},{id:"contacts",label:"Contacts",icon:<Users size={17}/>,children:[{id:"team",label:"Team Contacts",href:"#team"},{id:"personal",label:"My Contacts",href:"#personal"}]},{id:"projects",label:"Projects",icon:<BriefcaseBusiness size={17}/>,href:"#projects"},{id:"plans",label:"Plans",icon:<ShieldCheck size={17}/>,href:"#plans"},{id:"downloads",label:"Downloads",icon:<Folder size={17}/>,children:[{id:"identity",label:"Identity Card",href:"#identity"},{id:"certificates",label:"Certificates",href:"#certificates"}]},{id:"apps",label:"Connected Apps",icon:<LayoutGrid size={17}/>,href:"#apps"},{id:"settings",label:"Settings",icon:<Settings size={17}/>,href:"#settings"}];
const people=[{id:"1",name:"Alex Morgan",company:"Northstar Studio",city:"Hyderabad",status:"Active"},{id:"2",name:"Jamie Chen",company:"Fieldwork Design",city:"Bengaluru",status:"Pending"},{id:"3",name:"Taylor Reed",company:"Common Ground",city:"Chennai",status:"Active"},{id:"4",name:"Jordan Lee",company:"Paperplane",city:"Pune",status:"Active"},{id:"5",name:"Sam Rivera",company:"New Leaf",city:"Mumbai",status:"Pending"}];
export function DemoTable(){const [selected,setSelected]=useState<(typeof people)[number]|null>(null);const columns:UI.Column<(typeof people)[number]>[]=[{id:"name",header:"Name",accessor:r=>r.name,sortable:true,cell:r=><div className="flex items-center gap-2.5 whitespace-nowrap"><UI.Avatar name={r.name}/>{r.name}</div>},{id:"company",header:"Business name",accessor:r=>r.company,sortable:true},{id:"city",header:"City",accessor:r=>r.city,sortable:true},{id:"status",header:"Status",accessor:r=>r.status,cell:r=><UI.Badge variant={r.status==="Active"?"success":"warning"}>{r.status}</UI.Badge>},{id:"actions",header:"",accessor:()=>"",cell:r=><UI.DropdownMenu><UI.DropdownMenuTrigger asChild><UI.Button variant="ghost" size="icon" aria-label={`Actions for ${r.name}`}><EllipsisVertical size={16}/></UI.Button></UI.DropdownMenuTrigger><UI.DropdownMenuContent><UI.DropdownMenuItem onSelect={()=>setSelected(r)}>Business Info</UI.DropdownMenuItem></UI.DropdownMenuContent></UI.DropdownMenu>}];return <><UI.DataTable data={people} columns={columns} rowKey={r=>r.id} searchPlaceholder="Search contacts" pageSize={3} caption="Example contacts"/><UI.Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><UI.DialogContent><UI.DialogHeader><UI.DialogTitle>Business Information</UI.DialogTitle><UI.DialogDescription>Fictional contact details for this example.</UI.DialogDescription></UI.DialogHeader><UI.DialogBody>{selected&&<UI.DetailList items={[{label:"Name",value:selected.name},{label:"Company",value:selected.company},{label:"City",value:selected.city},{label:"Status",value:selected.status}]}/>}</UI.DialogBody></UI.DialogContent></UI.Dialog></>;}

export function ComponentDemo({slug}:{slug:string}){
  const [notice,setNotice]=useState("");const [active,setActive]=useState("home");const [filter,setFilter]=useState("All apps");const [query,setQuery]=useState("");const [period,setPeriod]=useState("This Fiscal Year");const [loading,setLoading]=useState(false);
  const feedback=notice&&<div className="mt-5"><UI.Alert title={notice} variant="success" onDismiss={()=>setNotice("")}/></div>;
  let demo:React.ReactNode;
  switch(slug){
    case "metric-card":demo=<div className="grid gap-4 sm:grid-cols-2"><UI.MetricCard value="128" label="Total members" tone="indigo"/><UI.MetricCard value="24" label="Review pending" tone="orange"/><UI.MetricCard value="102" label="Approved" tone="green"/><UI.MetricCard value="2" label="Rejected" tone="red"/></div>;break;
    case "organization-switcher":demo=<UI.OrganizationSwitcher organizations={[{id:"acme",name:"Acme Workspace",code:"000001",memberCount:24},{id:"design",name:"Design Team",code:"000002",memberCount:8}]} selectedId={filter==="Design Team"?"design":"acme"} onSelect={organization=>setFilter(organization.name)} onManage={()=>setNotice("Manage organizations selected")}/>;break;
    case "admin-toolbar":demo=<UI.AdminToolbar workspace={filter==="All apps"?"Acme Workspace":filter} workspaces={[{id:"acme",name:"Acme Workspace",code:"000001",memberCount:24},{id:"design",name:"Design Team",code:"000002",memberCount:8}]} onManageWorkspaces={()=>setNotice("Manage organizations selected")} onWorkspaceChange={setFilter} userName="Alex Morgan" onNotifications={()=>setNotice("No new notifications")} onSettings={()=>setNotice("Settings selected")} userActions={[{label:"View account",onSelect:()=>setNotice("Account selected")}]}/>;break;
    case "list-toolbar":demo=<UI.ListToolbar title={filter==="All apps"?"All members":filter} views={["All members","Waiting for approval","Approved","Rejected","Expired"]} onViewChange={setFilter}><UI.Button shape="rounded" size="sm" onClick={()=>setNotice("Quick create selected")}><Plus size={14}/>Quick Create</UI.Button><UI.Button shape="rounded" size="sm" onClick={()=>setNotice("New record selected")}><Plus size={14}/>New</UI.Button></UI.ListToolbar>;break;
    case "settings-group":demo=<div className="grid gap-4 sm:grid-cols-3"><UI.SettingsGroup title="Organization" icon={<Building2 size={18}/>} links={[{label:"Profile",href:"/docs/profile-card"},{label:"Contacts",href:"/docs/data-table"}]}/><UI.SettingsGroup title="Users & roles" icon={<Users size={18}/>} links={[{label:"Users",href:"/docs/data-table"},{label:"Roles",href:"/docs/checkbox"}]}/><UI.SettingsGroup title="Preferences" icon={<Settings size={18}/>} links={[{label:"General",href:"/docs/checkbox"}]}/></div>;break;
    case "file-upload":demo=<div className="max-w-md"><UI.FileUpload label="Template" accept="image/png,image/jpeg" onFileChange={file=>setNotice(file?`Selected ${file.name} locally`:"Selection removed")}/></div>;break;
    case "compact-form":demo=<UI.Dialog><UI.DialogTrigger asChild><UI.Button shape="rounded"><Plus size={16}/>Quick Create</UI.Button></UI.DialogTrigger><UI.DialogContent><UI.DialogHeader><UI.DialogTitle>Create Member</UI.DialogTitle><UI.DialogDescription>Local component example. No data leaves this page.</UI.DialogDescription></UI.DialogHeader><form onSubmit={e=>{e.preventDefault();setNotice("Example form validated locally")}}><UI.DialogBody><div className="grid gap-5 sm:grid-cols-2">{["First name","Surname","Contact number","Email address","City","District","Country","Postal code"].map((label,i)=><UI.CompactInput key={label} aria-label={label} placeholder={`${label}${[0,1,2,4].includes(i)?"*":""}`} required={[0,1,2,4].includes(i)} type={i===3?"email":"text"}/>)}</div>{notice&&<p role="status" className="mt-4 text-green-600">{notice}</p>}</UI.DialogBody><UI.DialogFooter><UI.Button type="submit">Create</UI.Button><UI.DialogClose asChild><UI.Button type="button" variant="secondary">Cancel</UI.Button></UI.DialogClose></UI.DialogFooter></form></UI.DialogContent></UI.Dialog>;break;
    case "auth-card":demo=<UI.AuthCard brand={<strong className="text-2xl">Acme / Workspace</strong>} footer="New to Acme? Contact your administrator."><form className="space-y-6" onSubmit={e=>{e.preventDefault();setNotice("Sign-in example submitted locally")}}><UI.Field label="Username" id="auth-user" required><UI.Input autoComplete="username"/></UI.Field><UI.Field label="Password" id="auth-pass" required><UI.PasswordInput autoComplete="current-password"/></UI.Field><UI.Button type="submit" size="lg" className="w-full">Sign in</UI.Button></form></UI.AuthCard>;break;
    case "button":demo=<div className="space-y-7"><div className="flex flex-wrap items-center gap-3"><UI.Button onClick={()=>setNotice("Primary action selected")}>Continue</UI.Button><UI.Button variant="outline" onClick={()=>setNotice("Outline action selected")}>Cancel</UI.Button><UI.Button variant="secondary" shape="rounded" onClick={()=>setNotice("Secondary action selected")}>View details</UI.Button><UI.Button variant="ghost" onClick={()=>setNotice("Ghost action selected")}>More options</UI.Button><UI.Button variant="link" onClick={()=>setNotice("Link action selected")}>Learn more</UI.Button></div><div className="flex flex-wrap items-center gap-3"><UI.Button size="sm" onClick={()=>setNotice("Small action selected")}>Small</UI.Button><UI.Button size="lg" onClick={()=>setNotice("Large action selected")}><Plus size={17}/>Create record</UI.Button><UI.Button variant="outline" size="icon" aria-label="Download example" onClick={()=>setNotice("Download action selected")}><Download size={17}/></UI.Button><UI.Button disabled>Disabled</UI.Button><UI.Button loading={loading} onClick={()=>{setLoading(true);setTimeout(()=>{setLoading(false);setNotice("Example action complete")},1200)}}>{loading?"Saving":"Try loading"}</UI.Button></div></div>;break;
    case "input":demo=<div className="grid max-w-2xl gap-6 sm:grid-cols-2"><UI.Field label="Business name" id="demo-business" required><UI.Input placeholder="Northstar Studio"/></UI.Field><UI.Field label="Email address" id="demo-email" hint="Use your work email."><UI.Input type="email" placeholder="hello@example.com"/></UI.Field><UI.Field label="Password" id="demo-password"><UI.PasswordInput placeholder="Enter a password"/></UI.Field><UI.Field label="Contact number" id="demo-error" error="Enter a valid contact number."><UI.Input defaultValue="123"/></UI.Field><UI.Field label="Address" id="demo-address"><UI.Textarea placeholder="Street, city, and postal code"/></UI.Field><UI.Field label="Disabled field" id="demo-disabled"><UI.Input disabled value="Read-only example"/></UI.Field></div>;break;
    case "select":demo=<div className="max-w-80 space-y-6"><UI.Label htmlFor="demo-category">Category</UI.Label><UI.Select defaultValue="design" onValueChange={v=>setNotice(`Selected ${v}`)}><UI.SelectTrigger id="demo-category"><UI.SelectValue placeholder="Select a category"/></UI.SelectTrigger><UI.SelectContent>{["design","technology","consulting"].map(v=><UI.SelectItem key={v} value={v}>{v[0].toUpperCase()+v.slice(1)}</UI.SelectItem>)}</UI.SelectContent></UI.Select><fieldset className="space-y-3"><legend className="mb-3 text-sm font-medium">Services · multi-selection composition</legend>{["Branding","Development","Photography"].map(s=><label key={s} className="flex items-center gap-3"><UI.Checkbox/>{s}</label>)}</fieldset></div>;break;
    case "checkbox":demo=<div className="space-y-5"><label className="flex items-center gap-3"><UI.Checkbox defaultChecked/>Include archived records</label><label className="flex items-center gap-3"><UI.Checkbox/>Send a copy to my email</label><label className="flex items-center gap-3 text-slate-400"><UI.Checkbox disabled/>Unavailable option</label><label className="flex items-center gap-3"><UI.Switch defaultChecked/>Email notifications</label></div>;break;
    case "badge":demo=<div className="flex flex-wrap gap-3">{([['success','Active'],['warning','Pending'],['danger','Expired'],['neutral','Draft'],['info','In progress']] as const).map(([variant,label])=><UI.Badge key={variant} variant={variant}>{label}</UI.Badge>)}</div>;break;
    case "avatar":demo=<div className="flex items-center gap-6"><UI.Avatar name="Alex Morgan" size="sm"/><UI.Avatar name="Jamie Chen"/><UI.Avatar name="Taylor Reed" size="lg"/></div>;break;
    case "card":demo=<UI.Card className="w-full max-w-md overflow-hidden"><UI.CardHeader><h3 className="text-base font-medium">Company details</h3></UI.CardHeader><UI.CardContent><UI.DetailList items={[{label:"Business name",value:"Northstar Studio"},{label:"Category",value:"Design"},{label:"Email",value:"hello@example.com"},{label:"Status",value:<UI.Badge variant="success">Active</UI.Badge>}]}/></UI.CardContent></UI.Card>;break;
    case "tabs":demo=<UI.Tabs defaultValue="overview" className="w-full"><UI.TabsList aria-label="Example sections">{["overview","activity","settings"].map(v=><UI.TabsTrigger key={v} value={v}>{v[0].toUpperCase()+v.slice(1)}</UI.TabsTrigger>)}</UI.TabsList><UI.TabsContent value="overview"><p className="text-slate-500">Your workspace at a glance.</p></UI.TabsContent><UI.TabsContent value="activity"><UI.Timeline items={[{id:"1",date:"23 Sep 2026",title:"Workspace created"}]}/></UI.TabsContent><UI.TabsContent value="settings"><label className="flex items-center gap-3"><UI.Switch/>Enable notifications</label></UI.TabsContent></UI.Tabs>;break;
    case "accordion":demo=<UI.Accordion type="single" collapsible className="w-full max-w-xl">{["Address","Nominee","Other details","Social media","Record info"].map((v,i)=><UI.AccordionItem key={v} value={v}><UI.AccordionTrigger>{v}</UI.AccordionTrigger><UI.AccordionContent>{i===0?<UI.DetailList items={[{label:"City",value:"Hyderabad"},{label:"Country",value:"India"}]}/>:<p>Example {v.toLowerCase()} information.</p>}</UI.AccordionContent></UI.AccordionItem>)}</UI.Accordion>;break;
    case "dialog":demo=<UI.Dialog><UI.DialogTrigger asChild><UI.Button>View business information</UI.Button></UI.DialogTrigger><UI.DialogContent><UI.DialogHeader><UI.DialogTitle>Business Information</UI.DialogTitle><UI.DialogDescription>Details for Northstar Studio.</UI.DialogDescription></UI.DialogHeader><UI.DialogBody><div className="space-y-4"><UI.Card className="bg-slate-50 p-4"><h3 className="mb-5 flex items-center gap-2 text-base font-semibold"><Building2 size={18}/>Company Details</h3><UI.DetailList items={[{label:"Company name",value:"Northstar Studio"},{label:"Business email",value:"hello@example.com"}]}/></UI.Card><UI.Card className="bg-slate-50 p-4"><h3 className="mb-5 text-base font-semibold">Contact Person</h3><UI.DetailList items={[{label:"Name",value:"Alex Morgan"},{label:"Role",value:"Design director"}]}/></UI.Card></div></UI.DialogBody><UI.DialogFooter><UI.DialogClose asChild><UI.Button variant="outline">Close</UI.Button></UI.DialogClose></UI.DialogFooter></UI.DialogContent></UI.Dialog>;break;
    case "dropdown-menu":demo=<UI.DropdownMenu><UI.DropdownMenuTrigger asChild><UI.Button variant="outline">Actions <EllipsisVertical size={16}/></UI.Button></UI.DropdownMenuTrigger><UI.DropdownMenuContent><UI.DropdownMenuItem onSelect={()=>setNotice("Business information selected")}><Building2 size={16}/>Business Info</UI.DropdownMenuItem><UI.DropdownMenuItem onSelect={()=>setNotice("Referral example selected")}><BriefcaseBusiness size={16}/>Refer a Business</UI.DropdownMenuItem><UI.DropdownMenuSeparator/><UI.DropdownMenuItem disabled><Mail size={16}/>Send message</UI.DropdownMenuItem></UI.DropdownMenuContent></UI.DropdownMenu>;break;
    case "tooltip":demo=<UI.Tooltip content="Download example file"><UI.Button variant="outline" size="icon" aria-label="Download example file" onClick={()=>setNotice("Example action selected")}><Download size={18}/></UI.Button></UI.Tooltip>;break;
    case "feedback":demo=<div className="max-w-xl space-y-4"><UI.Alert title="Saved locally" variant="success">Your example is up to date.</UI.Alert><UI.Alert title="Review the required fields" variant="danger">Enter a valid email address.</UI.Alert><UI.Alert title="Preview environment">Changes apply to this example only.</UI.Alert><div aria-label="Loading example" className="flex items-center gap-3 pt-2"><UI.Skeleton className="size-10 rounded-full"/><div className="space-y-2"><UI.Skeleton className="h-3 w-44"/><UI.Skeleton className="h-3 w-28"/></div></div></div>;break;
    case "data-table":demo=<DemoTable/>;break;
    case "sidebar":demo=<div className="flex min-h-[600px] overflow-hidden rounded-md border border-slate-200"><UI.Sidebar brand={<span className="text-lg font-bold">Acme / Workspace</span>} user={{name:"Alex Morgan",subtitle:"Workspace member"}} items={exampleNavigation} activeId={active} onNavigate={item=>setActive(item.id)} userActions={[{label:"View account",onSelect:()=>setNotice("Account menu selected")}]} className="min-h-[600px]"/><div className="hidden flex-1 bg-slate-50 p-8 sm:block"><p className="text-xs text-slate-400">Selected navigation</p><h3 className="mt-2 text-lg font-medium capitalize">{active}</h3><p className="mt-4 max-w-xs leading-6 text-slate-500">Open a group to explore nested links. This navigation updates only the local example.</p></div></div>;break;
    case "app-shell":demo=<div><p className="mb-5 text-slate-500">View the full responsive shell with dashboard, contacts, and settings examples.</p><UI.Button asChild><a href="/examples">Open shell example <ExternalLink size={16}/></a></UI.Button></div>;break;
    case "page-header":demo=<UI.PageHeader title="Business details" description="Manage your business information" actions={<UI.Button onClick={()=>setNotice("Edit action selected")}>Edit details</UI.Button>}/>;break;
    case "empty-state":demo=<><UI.SearchInput className="max-w-md" placeholder="Search records" value={query} onChange={e=>setQuery(e.target.value)}/><UI.EmptyState title={query?`No results for “${query}”`:"No records found"} description="No records match your search criteria. Try adjusting your search terms or check back later." icon={<FileSearch size={40}/>} action={<UI.Button variant="outline" onClick={()=>{setQuery("");setNotice("Search cleared")}}><RotateCcw size={16}/>Clear Search</UI.Button>}/></>;break;
    case "app-card":demo=<div className="grid gap-6 sm:grid-cols-2"><UI.AppCard title="Digital Card" description="Create and share a professional profile with your network." icon={<Users size={28}/>} features={["Digital business cards","Professional profiles","Networking"]} accent="lime" locked onLaunch={()=>setNotice("Digital Card launch selected")}/><UI.AppCard title="Website" description="Create and manage your business's online presence." icon={<Globe size={28}/>} features={["Content management","Website analytics","SEO tools"]} accent="red" onLaunch={()=>setNotice("Website launch selected")}/></div>;break;
    case "filter-chip":demo=<div className="flex flex-wrap gap-2">{["All apps","Business","Tools"].map((v,i)=><UI.FilterChip key={v} active={filter===v} count={i?2:4} onClick={()=>setFilter(v)}>{v}</UI.FilterChip>)}<p role="status" className="mt-4 w-full text-xs text-slate-500">Selected: {filter}</p></div>;break;
    case "timeline":demo=<UI.Timeline items={[{id:"1",date:"23 Sep 2026, 10:30 AM",title:"Profile updated",description:"by Alex Morgan"},{id:"2",date:"22 Sep 2026, 4:15 PM",title:"Business details added",description:"by Jamie Chen"},{id:"3",date:"21 Sep 2026, 9:00 AM",title:"Workspace created",description:"by Alex Morgan"}]}/>;break;
    case "profile-card":demo=<UI.ProfileCard name="Alex Morgan" subtitle="Design director · Northstar Studio" actions={<UI.Badge variant="success">Active</UI.Badge>}><UI.DetailList items={[{label:"Email",value:"alex@example.com"},{label:"City",value:"Hyderabad"},{label:"Organization",value:"Acme Network"},{label:"Membership",value:"Professional"}]}/></UI.ProfileCard>;break;
    case "chart-panel":demo=<UI.ChartPanel title="Income" total={period==="This Fiscal Year"?"₹0.00":"₹12,000.00"} points={["Apr","May","Jun","Jul","Aug","Sep"].map((label,i)=>({label,value:period==="This Fiscal Year"?0:[1,2,1,3,2,4][i]}))} period={period} onPeriodChange={setPeriod}/>;break;
    case "identity-card":demo=<UI.IdentityCard organization="Acme Network" name="Alex Morgan" designation="Professional member" memberId="ACME-000001"><p className="mt-4 flex items-center justify-center gap-1 text-xs text-green-600"><Check size={13}/>Active member</p></UI.IdentityCard>;break;
    default:demo=null;
  }
  return <UI.AjsProvider>{demo}{feedback}</UI.AjsProvider>;
}
