"use client";
import Link from "next/link";
import Image from "next/image";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { Command } from "cmdk";
import { Dialog } from "radix-ui";
import { ArrowUpRight, Box, Layers3, Menu, Search, X } from "lucide-react";
import { catalog } from "@/lib/catalog";

export function DocsShell({children}:{children:React.ReactNode}){
  const pathname=usePathname(),router=useRouter();const [searchOpen,setSearchOpen]=useState(false),[navOpen,setNavOpen]=useState(false);
  useEffect(()=>{const listener=(e:KeyboardEvent)=>{if(e.key.toLowerCase()==="k"&&(e.metaKey||e.ctrlKey)){e.preventDefault();setSearchOpen(v=>!v)}};document.addEventListener("keydown",listener);return()=>document.removeEventListener("keydown",listener)},[]);
  const navigation=<nav aria-label="Documentation" className="px-5 py-7"><Link href="/docs" onClick={()=>setNavOpen(false)} className={`mb-6 flex items-center gap-2 rounded-md px-3 py-2 font-medium ${pathname==="/docs"?"bg-slate-100 text-primary":"text-slate-500 hover:bg-slate-50"}`}><Layers3 size={15}/>Overview</Link>{(["Get started","Components","Patterns"] as const).map(group=><div key={group} className="mb-7"><p className="mb-2 px-3 text-[10px] font-semibold tracking-widest text-slate-400 uppercase">{group}</p>{catalog.filter(e=>e.group===group).map(item=><Link key={item.slug} href={`/docs/${item.slug}`} onClick={()=>setNavOpen(false)} aria-current={pathname===`/docs/${item.slug}`?"page":undefined} className={`mb-0.5 block rounded-md px-3 py-1.5 text-[13px] ${pathname===`/docs/${item.slug}`?"bg-slate-100 font-semibold text-primary":"text-slate-500 hover:bg-slate-50 hover:text-primary"}`}>{item.title}</Link>)}</div>)}</nav>;
  return <div className="min-h-dvh bg-white"><a href="#docs-content" className="sr-only z-[100] rounded bg-primary p-3 text-white focus:not-sr-only focus:fixed focus:top-2 focus:left-2">Skip to content</a><header className="sticky top-0 z-30 flex h-16 items-center justify-between gap-4 border-b border-slate-200 bg-white px-4 lg:px-8"><div className="flex items-center gap-3"><button aria-label="Open documentation navigation" onClick={()=>setNavOpen(true)} className="rounded p-2 lg:hidden"><Menu size={20}/></button><Link href="/" className="flex items-center gap-3"><Image src="/assets/ajs-logo.png" alt="AJS Innovations" width={85} height={40} priority className="h-10 w-auto brightness-0"/><span className="border-l border-slate-200 pl-3 text-sm font-medium text-slate-500">UI</span></Link><span className="hidden rounded border border-slate-200 px-2 py-0.5 text-[10px] text-slate-500 sm:inline">0.1.1</span></div><div className="flex items-center gap-6"><Link href="/examples" className="hidden items-center gap-1 text-xs font-medium text-slate-500 hover:text-primary md:flex">Examples <ArrowUpRight size={13}/></Link><button onClick={()=>setSearchOpen(true)} aria-label="Search documentation, Command K or Control K" className="flex h-9 items-center gap-2 rounded-md border border-border bg-white px-3 text-xs text-slate-400 shadow-[0_2px_4px_rgba(0,0,0,0.075)] hover:border-slate-400"><Search size={15}/><span className="hidden sm:inline">Search documentation...</span><kbd className="ml-4 hidden rounded border border-slate-200 bg-slate-50 px-1.5 py-0.5 text-[10px] sm:inline">⌘ K</kbd></button></div></header><div className="mx-auto flex max-w-[1600px]"><aside className="sticky top-16 hidden h-[calc(100dvh-64px)] w-[240px] shrink-0 overflow-y-auto border-r border-slate-200 lg:block">{navigation}</aside><main id="docs-content" className="min-w-0 flex-1 px-5 py-9 sm:px-10 lg:px-14 lg:py-12">{children}<footer className="mt-14 flex justify-between gap-4 border-t border-slate-200 pt-6 text-[11px] text-slate-400"><span>AJS Innovations · UI library</span><Link href="/docs/coverage" className="hover:text-primary">Source coverage</Link></footer></main></div>
      <Dialog.Root open={navOpen} onOpenChange={setNavOpen}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-black/35"/><Dialog.Content className="fixed inset-y-0 left-0 z-50 w-[275px] overflow-y-auto bg-white outline-none"><Dialog.Title className="px-8 pt-6 text-lg font-semibold">Documentation</Dialog.Title><Dialog.Description className="sr-only">Browse component documentation.</Dialog.Description>{navigation}<Dialog.Close aria-label="Close navigation" className="absolute top-5 right-4 rounded p-2"><X size={18}/></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>
      <Command.Dialog filter={(value, search, keywords) => { const term = search.toLowerCase().trim(); const title = value.toLowerCase(); if (title === term) return 1; if (title.includes(term)) return 0.9; return term.split(/\s+/).every(word => (keywords || []).join(" ").toLowerCase().includes(word)) ? 0.3 : 0; }} open={searchOpen} onOpenChange={setSearchOpen} label="Search documentation" overlayClassName="fixed inset-0 z-50 bg-black/35" contentClassName="fixed top-[15vh] left-1/2 z-50 w-[calc(100%-32px)] max-w-[560px] -translate-x-1/2 overflow-hidden rounded-lg border border-slate-200 bg-white shadow-2xl">
        <Dialog.Title className="sr-only">Search documentation</Dialog.Title><Dialog.Description className="sr-only">Find a component or guide. Use arrow keys and Enter to navigate.</Dialog.Description><div className="flex items-center gap-3 border-b border-slate-200 px-4"><Search size={19} className="text-slate-400"/><Command.Input autoFocus placeholder="Search components, patterns, and guides..." className="h-14 min-w-0 flex-1 bg-transparent text-sm outline-none"/><button aria-label="Close search" onClick={()=>setSearchOpen(false)} className="rounded border border-slate-200 px-1.5 text-[10px] text-slate-400">Esc</button></div><Command.List className="max-h-[360px] overflow-y-auto p-2"><Command.Empty className="p-8 text-center text-sm text-slate-500">No matching documentation.</Command.Empty>{(["Get started","Components","Patterns"] as const).map(group=><Command.Group key={group} heading={group} className="mb-2 [&_[cmdk-group-heading]]:px-3 [&_[cmdk-group-heading]]:py-2 [&_[cmdk-group-heading]]:text-[10px] [&_[cmdk-group-heading]]:font-semibold [&_[cmdk-group-heading]]:text-slate-400 [&_[cmdk-group-heading]]:uppercase">{catalog.filter(d=>d.group===group).map(d=><Command.Item key={d.slug} value={d.title} keywords={[d.description]} onSelect={()=>{setSearchOpen(false);router.push(`/docs/${d.slug}`)}} className="flex cursor-pointer items-center gap-3 rounded-md px-3 py-3 text-[13px] data-[selected=true]:bg-slate-100"><Box size={16} className="text-slate-400"/>{d.title}<span className="ml-auto text-[10px] text-slate-400">{d.group}</span></Command.Item>)}</Command.Group>)}</Command.List><div className="border-t border-slate-200 bg-slate-50 px-4 py-2.5 text-[10px] text-slate-500">↑ ↓ to navigate <span className="ml-4">↵ to open</span><span className="ml-4">esc to close</span></div>
      </Command.Dialog>
    </div>;
}
