"use client";
import * as React from "react";
import { Bell, ChevronDown, Upload, X, Settings } from "lucide-react";
import { Button, Avatar, Card, Input } from "./primitives";
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "./controls";
import { cn } from "./utils";

export function MetricCard({value,label,tone="indigo"}:{value:React.ReactNode;label:string;tone?:"indigo"|"orange"|"green"|"red"}){return <div className={cn("rounded-2xl px-6 py-6 text-center shadow-sm",{indigo:"bg-indigo-100 text-indigo-800",orange:"bg-orange-100 text-orange-800",green:"bg-green-100 text-green-800",red:"bg-red-100 text-red-800"}[tone])}><p className="text-4xl leading-tight font-bold tabular-nums">{value}</p><p className="mt-1 text-base font-medium">{label}</p></div>;}
export interface AdminToolbarProps {workspace:string;workspaces?:string[];onWorkspaceChange?:(name:string)=>void;onNotifications?:()=>void;onSettings?:()=>void;userName:string;userActions?:{label:string;onSelect:()=>void}[]}
export function AdminToolbar({workspace,workspaces=[],onWorkspaceChange,onNotifications,onSettings,userName,userActions=[]}:AdminToolbarProps){return <header className="flex h-[52px] items-center justify-end gap-3 border-b border-ajs-divider bg-[#f7f7fd] px-4"><DropdownMenu><DropdownMenuTrigger className="flex items-center gap-2 rounded px-2 py-2 text-xs outline-none focus-visible:ring-2 focus-visible:ring-ajs-primary" disabled={!workspaces.length}>{workspace}<ChevronDown size={15}/></DropdownMenuTrigger><DropdownMenuContent>{workspaces.map(w=><DropdownMenuItem key={w} onSelect={()=>onWorkspaceChange?.(w)}>{w}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><span className="h-5 w-px bg-ajs-divider"/><Button variant="ghost" size="icon" aria-label="Notifications" onClick={onNotifications}><Bell size={20}/></Button><Button variant="ghost" size="icon" aria-label="Settings" onClick={onSettings}><Settings size={20}/></Button><DropdownMenu><DropdownMenuTrigger className="rounded-full outline-none focus-visible:ring-2 focus-visible:ring-ajs-primary" aria-label="Account menu" disabled={!userActions.length}><Avatar name={userName} size="sm"/></DropdownMenuTrigger><DropdownMenuContent align="end">{userActions.map(a=><DropdownMenuItem key={a.label} onSelect={a.onSelect}>{a.label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></header>;}
export function ListToolbar({title,views=[],onViewChange,children}:{title:string;views?:string[];onViewChange?:(view:string)=>void;children?:React.ReactNode}){return <div className="flex min-h-[68px] flex-wrap items-center justify-between gap-3 border-b border-ajs-divider bg-ajs-card px-4 py-3"><DropdownMenu><DropdownMenuTrigger disabled={!views.length} className="flex items-center gap-2 rounded px-2 py-1 text-base font-bold outline-none focus-visible:ring-2 focus-visible:ring-ajs-primary">{title}{!!views.length&&<ChevronDown size={14}/>}</DropdownMenuTrigger><DropdownMenuContent>{views.map(v=><DropdownMenuItem key={v} onSelect={()=>onViewChange?.(v)}>{v}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><div className="flex flex-wrap items-center gap-2">{children}</div></div>;}
export function SettingsGroup({title,icon,links}:{title:string;icon:React.ReactNode;links:{label:string;href:string}[]}){return <Card className="rounded-xl border-indigo-50 p-4 shadow-[0_4px_20px_rgba(99,102,241,0.06)]"><h3 className="mb-6 flex items-center gap-2 text-base font-semibold"><span className="flex size-8 items-center justify-center rounded-md bg-indigo-50 text-indigo-500">{icon}</span>{title}</h3><nav aria-label={title} className="space-y-4">{links.map(l=><a key={l.href} href={l.href} className="block text-sm outline-none hover:underline focus-visible:ring-2 focus-visible:ring-ajs-primary">{l.label}</a>)}</nav></Card>;}
export interface FileUploadProps {label:string;accept?:string;maxBytes?:number;onFileChange?:(file:File|null)=>void;disabled?:boolean}
export function FileUpload({label,accept="image/*",maxBytes=1024*1024,onFileChange,disabled}:FileUploadProps){const id=React.useId();const input=React.useRef<HTMLInputElement>(null);const [file,setFile]=React.useState<File|null>(null),[error,setError]=React.useState("");const choose=(candidate?:File)=>{if(!candidate)return;const allowed=accept.split(",").map(s=>s.trim()).filter(Boolean);if(allowed.length&&!allowed.some(rule=>rule.startsWith(".")?candidate.name.toLowerCase().endsWith(rule.toLowerCase()):rule.endsWith("/*")?candidate.type.startsWith(rule.slice(0,-1)):candidate.type===rule)){setError("This file type is not supported.");return}if(candidate.size>maxBytes){setError(`Choose a file smaller than ${Math.round(maxBytes/1024)} KB.`);return}setError("");setFile(candidate);onFileChange?.(candidate)};return <div><div className={cn("flex min-h-40 flex-col items-center justify-center rounded-md border border-dashed border-ajs-border bg-ajs-card p-6 text-center",disabled&&"opacity-50")} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!disabled)choose(e.dataTransfer.files[0])}}><Upload className="mb-3 size-7 text-slate-400"/><label htmlFor={id} className="cursor-pointer text-sm font-medium"><span>Drag {label} Here</span><span className="my-2 block text-xs font-normal text-ajs-muted">or</span><span className="inline-flex rounded-full bg-ajs-primary px-4 py-2 text-xs text-white">Choose file</span></label><input ref={input} id={id} type="file" accept={accept} disabled={disabled} className="sr-only" onChange={e=>choose(e.target.files?.[0])}/><p className="mt-3 text-[10px] text-ajs-muted">Maximum file size: {Math.round(maxBytes/1024)} KB</p></div>{file&&<div className="mt-2 flex items-center justify-between gap-2 rounded border border-ajs-divider px-3 py-2 text-xs"><span className="truncate">{file.name}</span><button type="button" disabled={disabled} aria-label="Remove selected file" onClick={()=>{setFile(null);setError("");if(input.current)input.current.value="";onFileChange?.(null)}}><X size={14}/></button></div>}{error&&<p role="alert" className="mt-2 text-xs text-ajs-danger">{error}</p>}</div>;}
export function CompactInput({className,...props}:React.ComponentProps<typeof Input>){return <Input className={cn("h-[42px]",className)} {...props}/>;}
export function AuthCard({brand,title="Sign in",children,footer}:{brand:React.ReactNode;title?:string;children:React.ReactNode;footer?:React.ReactNode}){return <div className="mx-auto w-full max-w-[416px] rounded-2xl bg-ajs-card px-6 py-8 shadow-sm sm:p-12"><div className="flex justify-center">{brand}</div><h1 className="my-5 text-center text-lg font-bold uppercase">{title}</h1><hr className="border-t border-ajs-divider"/><div className="mt-8">{children}</div>{footer&&<div className="mt-6 text-xs">{footer}</div>}</div>;}
