"use client";
import * as React from "react";
import { Checkbox as CheckboxPrimitive, Switch as SwitchPrimitive, Select as SelectPrimitive, Tabs as TabsPrimitive, Accordion as AccordionPrimitive, Dialog as DialogPrimitive, DropdownMenu as MenuPrimitive, Tooltip as TooltipPrimitive } from "radix-ui";
import { Check, ChevronDown, X } from "lucide-react";
import { cn } from "./utils";

export const Checkbox=React.forwardRef<React.ComponentRef<typeof CheckboxPrimitive.Root>,React.ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root>>(function Checkbox({className,...props},ref){return <CheckboxPrimitive.Root ref={ref} className={cn("inline-flex size-[18px] shrink-0 items-center justify-center rounded-[3px] border border-ajs-border bg-ajs-card text-white outline-none focus-visible:ring-2 focus-visible:ring-ajs-primary focus-visible:ring-offset-2 disabled:opacity-50 data-[state=checked]:border-ajs-primary data-[state=checked]:bg-ajs-primary",className)} {...props}><CheckboxPrimitive.Indicator><Check size={14}/></CheckboxPrimitive.Indicator></CheckboxPrimitive.Root>;});
export const Switch=React.forwardRef<React.ComponentRef<typeof SwitchPrimitive.Root>,React.ComponentPropsWithoutRef<typeof SwitchPrimitive.Root>>(function Switch({className,...props},ref){return <SwitchPrimitive.Root ref={ref} className={cn("inline-flex h-6 w-11 shrink-0 items-center rounded-full bg-slate-300 p-0.5 outline-none focus-visible:ring-2 focus-visible:ring-ajs-primary focus-visible:ring-offset-2 disabled:opacity-50 data-[state=checked]:bg-ajs-primary",className)} {...props}><SwitchPrimitive.Thumb className="block size-5 rounded-full bg-white shadow-sm transition-transform duration-150 data-[state=checked]:translate-x-5 motion-reduce:transition-none"/></SwitchPrimitive.Root>;});

export const Select=SelectPrimitive.Root;
export const SelectValue=SelectPrimitive.Value;
export const SelectTrigger=React.forwardRef<React.ComponentRef<typeof SelectPrimitive.Trigger>,React.ComponentPropsWithoutRef<typeof SelectPrimitive.Trigger>>(function SelectTrigger({className,children,...props},ref){return <SelectPrimitive.Trigger ref={ref} className={cn("flex h-[50px] w-full items-center justify-between gap-2 rounded-md border border-ajs-border bg-ajs-card px-4 text-sm shadow-[0_2px_4px_rgba(0,0,0,0.075)] outline-none focus:ring-1 focus:ring-ajs-primary disabled:opacity-50 data-[placeholder]:text-slate-400",className)} {...props}>{children}<SelectPrimitive.Icon><ChevronDown className="size-4 text-slate-400"/></SelectPrimitive.Icon></SelectPrimitive.Trigger>;});
export function SelectContent({className,children,...props}:React.ComponentProps<typeof SelectPrimitive.Content>){return <SelectPrimitive.Portal><SelectPrimitive.Content position="popper" sideOffset={4} className={cn("ajs-root z-50 max-h-72 min-w-[var(--radix-select-trigger-width)] overflow-auto rounded-md border border-ajs-divider bg-ajs-card p-1 shadow-lg",className)} {...props}><SelectPrimitive.Viewport>{children}</SelectPrimitive.Viewport></SelectPrimitive.Content></SelectPrimitive.Portal>;}
export function SelectItem({className,children,...props}:React.ComponentProps<typeof SelectPrimitive.Item>){return <SelectPrimitive.Item className={cn("relative flex min-h-9 cursor-pointer items-center rounded px-3 pr-8 text-sm outline-none data-[disabled]:opacity-40 data-[highlighted]:bg-ajs-background",className)} {...props}><SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText><SelectPrimitive.ItemIndicator className="absolute right-2"><Check size={15}/></SelectPrimitive.ItemIndicator></SelectPrimitive.Item>;}

export const Tabs=TabsPrimitive.Root;
export function TabsList({className,...props}:React.ComponentProps<typeof TabsPrimitive.List>){return <TabsPrimitive.List className={cn("flex gap-8 overflow-x-auto border-b border-ajs-divider",className)} {...props}/>;}
export function TabsTrigger({className,...props}:React.ComponentProps<typeof TabsPrimitive.Trigger>){return <TabsPrimitive.Trigger className={cn("shrink-0 border-b-[3px] border-transparent px-1 py-4 text-[13px] font-medium text-ajs-foreground outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ajs-primary disabled:opacity-40 data-[state=active]:border-ajs-primary",className)} {...props}/>;}
export function TabsContent({className,...props}:React.ComponentProps<typeof TabsPrimitive.Content>){return <TabsPrimitive.Content className={cn("pt-6 outline-none focus-visible:ring-2 focus-visible:ring-ajs-primary",className)} {...props}/>;}
export const Accordion=AccordionPrimitive.Root;
export function AccordionItem({className,...props}:React.ComponentProps<typeof AccordionPrimitive.Item>){return <AccordionPrimitive.Item className={cn("border-b border-ajs-divider",className)} {...props}/>;}
export function AccordionTrigger({className,children,...props}:React.ComponentProps<typeof AccordionPrimitive.Trigger>){return <AccordionPrimitive.Header><AccordionPrimitive.Trigger className={cn("group flex w-full items-center justify-between gap-3 py-4 text-left text-xs font-semibold uppercase outline-none focus-visible:ring-2 focus-visible:ring-ajs-primary",className)} {...props}>{children}<ChevronDown className="size-4 shrink-0 text-ajs-muted transition-transform group-data-[state=open]:rotate-180 motion-reduce:transition-none"/></AccordionPrimitive.Trigger></AccordionPrimitive.Header>;}
export function AccordionContent({className,...props}:React.ComponentProps<typeof AccordionPrimitive.Content>){return <AccordionPrimitive.Content className={cn("pb-5 text-sm text-ajs-muted",className)} {...props}/>;}

export const Dialog=DialogPrimitive.Root;
export const DialogTrigger=DialogPrimitive.Trigger;
export const DialogClose=DialogPrimitive.Close;
export function DialogContent({className,children,...props}:React.ComponentProps<typeof DialogPrimitive.Content>){return <DialogPrimitive.Portal><DialogPrimitive.Overlay className="fixed inset-0 z-50 bg-black/35"/><DialogPrimitive.Content className={cn("ajs-root fixed top-1/2 left-1/2 z-50 max-h-[90dvh] w-[calc(100%-32px)] max-w-[600px] -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-md bg-ajs-card shadow-2xl outline-none",className)} {...props}>{children}<DialogPrimitive.Close className="absolute top-4 right-4 rounded p-1 text-white outline-none focus-visible:ring-2 focus-visible:ring-white" aria-label="Close dialog"><X size={18}/></DialogPrimitive.Close></DialogPrimitive.Content></DialogPrimitive.Portal>;}
export function DialogHeader({className,...props}:React.ComponentProps<"div">){return <div className={cn("bg-ajs-primary px-5 py-4 pr-14 text-white",className)} {...props}/>;}
export function DialogTitle({className,...props}:React.ComponentProps<typeof DialogPrimitive.Title>){return <DialogPrimitive.Title className={cn("text-lg font-medium",className)} {...props}/>;}
export function DialogDescription({className,...props}:React.ComponentProps<typeof DialogPrimitive.Description>){return <DialogPrimitive.Description className={cn("mt-1 text-xs opacity-80",className)} {...props}/>;}
export function DialogBody({className,...props}:React.ComponentProps<"div">){return <div className={cn("p-6",className)} {...props}/>;}
export function DialogFooter({className,...props}:React.ComponentProps<"div">){return <div className={cn("flex flex-wrap justify-end gap-3 border-t border-ajs-divider p-4",className)} {...props}/>;}

export const DropdownMenu=MenuPrimitive.Root;
export const DropdownMenuTrigger=MenuPrimitive.Trigger;
export function DropdownMenuContent({className,...props}:React.ComponentProps<typeof MenuPrimitive.Content>){return <MenuPrimitive.Portal><MenuPrimitive.Content sideOffset={5} className={cn("ajs-root z-50 min-w-44 rounded-md border border-ajs-divider bg-ajs-card py-2 shadow-lg",className)} {...props}/></MenuPrimitive.Portal>;}
export function DropdownMenuItem({className,...props}:React.ComponentProps<typeof MenuPrimitive.Item>){return <MenuPrimitive.Item className={cn("flex cursor-pointer items-center gap-3 px-4 py-2.5 text-[13px] outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-40 data-[highlighted]:bg-ajs-background",className)} {...props}/>;}
export function DropdownMenuSeparator(){return <MenuPrimitive.Separator className="my-1 h-px bg-ajs-divider"/>;}
export function Tooltip({children,content}: {children:React.ReactNode;content:React.ReactNode}){return <TooltipPrimitive.Provider delayDuration={250}><TooltipPrimitive.Root><TooltipPrimitive.Trigger asChild>{children}</TooltipPrimitive.Trigger><TooltipPrimitive.Portal><TooltipPrimitive.Content sideOffset={5} className="ajs-root z-50 rounded bg-ajs-primary px-3 py-1.5 text-xs text-white shadow-md">{content}<TooltipPrimitive.Arrow className="fill-ajs-primary"/></TooltipPrimitive.Content></TooltipPrimitive.Portal></TooltipPrimitive.Root></TooltipPrimitive.Provider>;}
