"use client";
import * as React from "react";
import { ArrowDown, ArrowUp, ChevronLeft, ChevronRight } from "lucide-react";
import { Button, SearchInput } from "./primitives";
import { cn } from "./utils";

export interface Column<T> { id:string; header:string; accessor:(row:T)=>string|number; cell?:(row:T)=>React.ReactNode; sortable?:boolean; className?:string }
export interface DataTableProps<T> { data:T[]; columns:Column<T>[]; rowKey:(row:T)=>string; searchPlaceholder?:string; pageSize?:number; emptyMessage?:string; caption?:string; variant?:"plain"|"rounded" }
export function DataTable<T>({data,columns,rowKey,searchPlaceholder,pageSize=10,emptyMessage="No records found",caption="Records",variant="plain"}:DataTableProps<T>){
  const [query,setQuery]=React.useState("");const [page,setPage]=React.useState(0);const [sort,setSort]=React.useState<{id:string;direction:1|-1}|null>(null);
  const filtered=React.useMemo(()=>{const rows=data.filter(row=>columns.some(c=>String(c.accessor(row)).toLowerCase().includes(query.toLowerCase())));const col=columns.find(c=>c.id===sort?.id);return col&&sort?[...rows].sort((a,b)=>{const av=col.accessor(a),bv=col.accessor(b);return (typeof av==="number"&&typeof bv==="number"?av-bv:String(av).localeCompare(String(bv)))*sort.direction}):rows},[data,columns,query,sort]);
  const size=Math.max(1,pageSize),lastPage=Math.max(0,Math.ceil(filtered.length/size)-1),currentPage=Math.min(page,lastPage),start=currentPage*size,rows=filtered.slice(start,start+size);
  return <div className="w-full min-w-0">{searchPlaceholder&&<div className="p-3"><SearchInput className="max-w-[400px]" placeholder={searchPlaceholder} aria-label={searchPlaceholder} value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></div>}<div className={cn("overflow-x-auto",variant==="rounded"&&"rounded-[13px] border border-ajs-divider bg-ajs-subtle p-2")}><table className="w-full border-collapse text-left text-[13px]"><caption className="sr-only">{caption}</caption><thead className={cn("bg-ajs-subtle",variant==="plain"&&"text-[11px] text-[#71758a] uppercase")}><tr>{columns.map(col=><th key={col.id} scope="col" aria-sort={sort?.id===col.id?(sort.direction===1?"ascending":"descending"):undefined} className={cn("whitespace-nowrap border-y border-ajs-divider px-3 py-3 font-semibold",col.className)}>{col.sortable?<button type="button" className="inline-flex items-center gap-2 outline-none focus-visible:ring-2 focus-visible:ring-ajs-primary" onClick={()=>{setSort({id:col.id,direction:sort?.id===col.id&&sort.direction===1?-1:1});setPage(0)}}>{col.header}{sort?.id===col.id&&(sort.direction===1?<ArrowUp size={14}/>:<ArrowDown size={14}/>)}</button>:col.header}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={rowKey(row)} className="border-b border-ajs-divider last:border-0">{columns.map(col=><td key={col.id} className={cn("px-3 py-3",col.className)}>{col.cell?col.cell(row):col.accessor(row)}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={columns.length} className="p-12 text-center text-ajs-muted">{emptyMessage}</td></tr>}</tbody></table></div><div className="flex items-center justify-between gap-3 px-3 py-3 text-xs text-ajs-muted"><span aria-live="polite">{filtered.length?start+1:0}–{Math.min(start+size,filtered.length)} of {filtered.length}</span><div className="flex gap-1"><Button type="button" variant="ghost" size="icon" aria-label="Previous page" disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={16}/></Button><Button type="button" variant="ghost" size="icon" aria-label="Next page" disabled={currentPage===lastPage} onClick={()=>setPage(currentPage+1)}><ChevronRight size={16}/></Button></div></div></div>;
}
