"use client";
import * as React from "react";
import { Inbox, ExternalLink, Clock, Tag, LockKeyhole, LayoutGrid, ChevronDown } from "lucide-react";
import { Button, Card, CardHeader, Avatar } from "./primitives";
import { cn } from "./utils";

export function PageHeader({title,description,children,actions,className}:{title:string;description?:string;children?:React.ReactNode;actions?:React.ReactNode;className?:string}){return <header className={cn("border-b border-ajs-divider bg-ajs-subtle px-4 pt-6",className)}><div className="flex flex-wrap items-start justify-between gap-4 pb-5"><div><h1 className="text-xl leading-7 font-semibold">{title}</h1>{description&&<p className="mt-2 text-xs text-ajs-muted">{description}</p>}</div>{actions}</div>{children}</header>;}
export function EmptyState({title="No results found",description,icon,action,compact=false}:{title?:string;description?:string;icon?:React.ReactNode;action?:React.ReactNode;compact?:boolean}){return <div className={cn("flex flex-col items-center px-6 text-center",compact?"py-10":"py-16")}><div className={cn("mb-6 flex items-center justify-center text-slate-400",!compact&&"size-24 rounded-full border-2 border-ajs-divider bg-ajs-background")}>{icon||<Inbox className={compact?"size-8":"size-10"}/>}</div><h3 className={cn(compact?"text-sm font-medium text-ajs-muted":"text-lg font-bold")}>{title}</h3>{description&&<p className="mt-3 max-w-[520px] text-[13px] leading-6 text-ajs-muted">{description}</p>}{action&&<div className="mt-6">{action}</div>}</div>;}
export function FilterChip({active,children,count,onClick}:{active?:boolean;children:React.ReactNode;count?:number;onClick?:()=>void}){return <button type="button" aria-pressed={!!active} onClick={onClick} className={cn("inline-flex h-10 items-center gap-2 rounded-full border border-ajs-border px-4 text-sm font-medium outline-none focus-visible:ring-2 focus-visible:ring-ajs-primary",active?"bg-[#efeff0]":"bg-ajs-card")}><LayoutGrid size={17} className="text-ajs-muted"/>{children}{count!==undefined&&<span className="ml-1 rounded-full bg-slate-200 px-2 text-[10px]">{count}</span>}</button>;}
export interface AppCardProps {title:string;description:string;icon:React.ReactNode;features:string[];category?:string;version?:string;updated?:string;locked?:boolean;onLaunch?:()=>void;accent?:"lime"|"red"|"blue"}
export function AppCard({title,description,icon,features,category="Business",version="1.0.0",updated="1 week ago",locked,onLaunch,accent="blue"}:AppCardProps){return <Card className="flex h-full flex-col rounded-md p-6 shadow-sm"><div className={cn("mb-5 flex size-16 items-center justify-center rounded-xl",{lime:"bg-lime-100 text-lime-500",red:"bg-red-100 text-red-500",blue:"bg-blue-100 text-blue-500"}[accent])}>{icon}</div><h3 className="text-base font-bold">{title}</h3><p className="mt-2 line-clamp-2 text-[13px] leading-5 text-ajs-muted">{description}</p><div className="mt-4 flex items-center gap-2"><span className="inline-flex items-center gap-2 rounded-full bg-indigo-50 px-3 py-1"><LayoutGrid size={14} className="text-ajs-muted"/>{category}</span>{locked&&<LockKeyhole size={12} aria-label="Restricted access" className="text-ajs-muted"/>}</div><div className="mt-3 mb-4 flex flex-wrap gap-1">{features.map(f=><span key={f} className="rounded bg-ajs-background px-2 py-1 text-[10px]">{f}</span>)}</div><div className="mt-auto flex flex-wrap gap-3 border-t border-ajs-divider pt-4 text-[10px] text-ajs-muted"><span className="flex items-center gap-1"><Tag size={12}/>v{version}</span><span className="flex items-center gap-1"><Clock size={12}/>Updated {updated}</span></div><Button variant="outline" shape="rounded" className="mt-5 w-full" onClick={onLaunch}><ExternalLink size={18}/>Launch App</Button></Card>;}
export interface TimelineEntry {id:string;date:string;title:string;description?:string}
export function Timeline({items}:{items:TimelineEntry[]}){return <ol aria-label="Activity timeline" className="list-none">{items.map((item,i)=><li key={item.id} className="relative flex gap-4 pb-6"><div className="relative flex w-5 shrink-0 justify-center"><span className="z-10 mt-1 size-2 rounded-full bg-slate-400"/>{i<items.length-1&&<span className="absolute top-3 bottom-[-24px] w-px bg-ajs-divider"/>}</div><div><time className="text-[11px] text-ajs-muted">{item.date}</time><p className="mt-1 text-[13px] font-medium">{item.title}</p>{item.description&&<p className="text-xs text-ajs-muted">{item.description}</p>}</div></li>)}</ol>;}
export function DetailList({items}:{items:{label:string;value:React.ReactNode}[]}){return <dl className="grid grid-cols-1 gap-x-6 gap-y-5 sm:grid-cols-2">{items.map(item=><div key={item.label}><dt className="text-[10px] font-medium text-ajs-muted uppercase">{item.label}</dt><dd className="mt-2 text-[13px] font-medium wrap-anywhere">{item.value}</dd></div>)}</dl>;}
export function ProfileCard({name,subtitle,src,children,actions}:{name:string;subtitle?:string;src?:string;children?:React.ReactNode;actions?:React.ReactNode}){return <Card className="p-6"><div className="flex flex-wrap items-center gap-4"><Avatar name={name} src={src} size="lg"/><div><h2 className="text-xl font-semibold">{name}</h2>{subtitle&&<p className="mt-1 text-ajs-muted">{subtitle}</p>}</div><div className="ml-auto">{actions}</div></div>{children&&<div className="mt-6 border-t border-ajs-divider pt-4">{children}</div>}</Card>;}
export interface ChartPoint {label:string;value:number}
export function ChartPanel({title,total,points,color="income",period="This Fiscal Year",onPeriodChange}:{title:string;total:string;points:ChartPoint[];color?:"income"|"expense";period?:string;onPeriodChange?:(period:string)=>void}){
  const max=Math.max(2,...points.map(p=>p.value));const values=points.map((p,i)=>`${40+i*(480/Math.max(1,points.length-1))},${200-(p.value/max)*170}`).join(" ");
  return <Card className="overflow-hidden"><CardHeader className="flex items-center justify-between gap-4"><h3 className="text-base font-medium">{title}</h3><div className="relative"><select aria-label={`${title} period`} value={period} onChange={e=>onPeriodChange?.(e.target.value)} disabled={!onPeriodChange} className="appearance-none bg-transparent pr-5 text-xs outline-none focus-visible:ring-2 focus-visible:ring-ajs-primary"><option>This Fiscal Year</option><option>Last Fiscal Year</option></select><ChevronDown size={13} className="pointer-events-none absolute top-1 right-0"/></div></CardHeader><div className="p-4"><svg viewBox="0 0 550 250" role="img" aria-label={`${title}: ${points.map(p=>`${p.label} ${p.value}`).join(", ")}`} className="h-auto w-full text-ajs-muted"><title>{title}</title>{[0,1,2].map(i=><g key={i}><line x1="40" x2="530" y1={200-i*85} y2={200-i*85} stroke="#e2e8f0"/><text x="20" y={204-i*85} fill="currentColor" fontSize="10">{Math.round(max*i/2)}</text></g>)}<polyline points={values} fill="none" stroke={color==="income"?"#16a34a":"#f97316"} strokeWidth="2"/>{points.map((p,i)=><text key={p.label} x={40+i*(480/Math.max(1,points.length-1))} y="230" textAnchor="middle" fill="currentColor" fontSize="10">{p.label}</text>)}</svg></div><div className="border-t border-ajs-divider p-4"><p className={cn("text-xs",color==="income"?"text-green-500":"text-orange-500")}>Total {title}</p><p className="mt-1 text-base font-semibold">{total}</p></div></Card>;
}
export function IdentityCard({organization,name,designation,memberId,children}:{organization:string;name:string;designation:string;memberId:string;children?:React.ReactNode}){return <Card className="mx-auto w-full max-w-72 overflow-hidden text-center"><div className="bg-ajs-primary px-4 py-5 text-white"><p className="text-base font-bold">{organization}</p></div><div className="p-6"><Avatar name={name} size="lg"/><h3 className="mt-4 text-lg font-semibold">{name}</h3><p className="mt-1 text-[11px] text-ajs-muted uppercase">{designation}</p><p className="mt-5 rounded bg-ajs-background p-2 font-mono text-xs">{memberId}</p>{children}</div></Card>;}
